### ISSUE TITLE
Convert Applet to JavaFX usage of Jframe

### ISSUE THREAD

**Issue by Realiante** [Realiante/Bubble-Duel#1]
1. Write a JFrame unit main class.
2. Write a Jpanel unit secondary class.
3. Convert BubbleApplet to Jpanel and rename it to BubblePanel
4.  Open the panel inside the main Jframe.

Attached, are good tutorials:
http://zetcode.com/tutorials/javagamestutorial/

**Comment by ukeruk** [comment]
Are you done with this? Didn't get to do anything lol.
Anyway, if you're done close the Issue, otherwise update what's needed to be done.
